SRV_HTTP_REPOSITORIES_HOST: 172.16.9.179
SRV_HTTP_REPOSITORIES_PORT: 30108
SRV_HTTP_REPOSITORIES_PROTOCOL: http://
SRV_HTTP_RESULT_HOST: 172.16.9.179
SRV_HTTP_RESULT_PORT: 30108
SRV_HTTP_RESULT_PROTOCOL: http://
GATEWAY_IP: 172.16.9.179
GATEWAY_PORT: 30108
ACCOUNT: __OAUTH_ACCOUNT__
PASSWORD: __OAUTH_PASSWORD__
OAUTH_TOKEN_URL: https://omapi.osinfra.cn/oneid/oidc/token
OAUTH_REDIRECT_URL: http://eulermaker.openeuler.openatom.cn/oauth/
PUBLIC_KEY_URL: https://omapi.osinfra.cn/oneid/public/key?community=openeuler
